library(arules)
library(arulesViz)
retail_transaction <- read.transactions("products.csv",sep=",")
summary(retail_transaction)
itemFrequency(retail_transaction[,1:3])
itemFrequencyPlot(retail_transaction, topN = 20)
image(retail_transaction[1:5])
image(sample(retail_transaction, 100))
ru1=apriori(retail_transaction)
itemsrules <- apriori(retail_transaction, parameter = list(support =0.0019, confidence = 0.04, minlen = 2))
itemsrules
summary(itemsrules)
inspect(itemsrules[1:3])
rules=itemsrules
plot(rules)
library(arulesViz)
subrules2 <- head(rules, n = 10, by = "lift")
plot(subrules2, method = "graph")
plot(subrules2, method = "paracoord")
plot(subrules2, method = "graph", engine = "htmlwidget")